variables:
    VERSION: "0.1"
    IMAGE_NAME: $CI_REGISTRY/cci/distributed-computing-framework/auto-scaler

stages:
    - test
    - build
    - push

unit test:
    stage: test
    image: python:3.8-slim
    tags:
        - dind
    script:
        - pip3 install -e .
        - cd tests
        - pytest

docker build:
    stage: build
    image: docker:latest
    only:
        - master
    tags:
        - dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - sh build_image.sh $VERSION

docker push:
    stage: push
    image: docker:latest
    only:
        - master
    tags:
        - dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $IMAGE_NAME:$VERSION
        - docker push $IMAGE_NAME:latest
