#!/bin/bash

DRIVER_MEMORY=${DRIVER_MEMORY-4g}
EXECUTOR_MEMORY=${EXECUTOR_MEMORY-8g}
RAPIDS_GPU_ALLOC_FRACTION=${RAPIDS_GPU_ALLOC_FRACTION-1}
RAPIDS_INCOMPATIBLE_OPS=${RAPIDS_INCOMPATIBLE_OPS-"false"}
RAPIDS_DEBUG=${RAPIDS_DEBUG-"NONE"}
RAPIDS_GPU_POOL=${RAPIDS_GPU_POOL-"ARENA"}

docker run \
  --rm \
  --network $NETWORK \
  -v "/tank:/tank" \
  -v "${MOUNT_POINT}:/mnt" \
  -e SPARK_MASTER_URI=$SPARK_MASTER_URI \
  -e CPU_ONLY=$CPU_ONLY \
  -e DRIVER_MEMORY=$DRIVER_MEMORY \
  -e EXECUTOR_MEMORY=$EXECUTOR_MEMORY \
  -e RAPIDS_GPU_ALLOC_FRACTION=$RAPIDS_GPU_ALLOC_FRACTION \
  -e RAPIDS_INCOMPATIBLE_OPS=$RAPIDS_INCOMPATIBLE_OPS \
  -e RAPIDS_DEBUG=$RAPIDS_DEBUG \
  -e RAPIDS_GPU_POOL=$RAPIDS_GPU_POOL \
  local/spark-submit:3.0.1-hadoop2.7 \
  $@