image: docker:latest

variables:
  SPARK_VERSION: "3.0.1"
  HADOOP_VERSION: "2.7"
  IMAGE_TAG_PATH: $CI_REGISTRY/cci/distributed-computing-framework/spark-images

stages:
  - build
  - push

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

docker build:
  stage: build
  only:
    - master
  tags:
    - dind
  script:
    - sh build-images.sh $SPARK_VERSION $HADOOP_VERSION

docker push:
  stage: push
  only:
    - master
  tags:
    - dind
  script:
    - docker push $IMAGE_TAG_PATH/spark-base:$SPARK_VERSION-hadoop$HADOOP_VERSION
    - docker push $IMAGE_TAG_PATH/spark-master:$SPARK_VERSION-hadoop$HADOOP_VERSION
    - docker push $IMAGE_TAG_PATH/spark-worker:$SPARK_VERSION-hadoop$HADOOP_VERSION
    - docker push $IMAGE_TAG_PATH/spark-submit:$SPARK_VERSION-hadoop$HADOOP_VERSION
